export const Classes = {
    rounded: {
        "set": "sizing",
        "value": "sizeScale",
        "rd": "border-radius",
        "rdtl": "border-top-left-radius",
        "rdb": "border-bottom-right-radius",
        "rdtr": "border-top-right-radius",
        "rdbl": "border-bottom-left-radius",
    },
    padding: {
        "set": "sizing",
        value: "space",
        "p": "padding",
        "pt": "padding-top",
        "pr": "padding-right",
        "pb": "padding-bottom",
        "pl": "padding-left",
    },
    margin: {
        "set": "sizing",
        value: "space",
        "m": "margin",
        "mt": "margin-top",
        "mr": "margin-right",
        "mb": "margin-bottom",
        "ml": "margin-left",
    },
    border: {
        "set": "sizing",
        value: "space",
        "b": "border",
        "bt": "border-top",
        "br": "border-right",
        "bb": "border-bottom",
        "bl": "border-left",
    },
    gap: {
        "set": "sizing",
        value: "space",
        "gp": "gap",
        "gpy": "row-gap",
        "gpx": "column-gap",
    },
    width: {
        "set": "sizing",
        value: "space",
        "w": "width",
        "min-w": "min-width",
        "max-w": "max-width",
    },
    height: {
        "set": "sizing",
        value: "space",
        "h": "height",
        "min-h": "min-height",
        "max-h": "max-height",
    },
    inset: {
        "set": "sizing",
        value: "space",
        "inset": "inset",
        "inset-x": "inset-inline",
        "inset-y": "inset-block",
        "top": "top",
        "right": "right",
        "bottom": "bottom",
        "left": "left",
    },
    translate: {
        "set": "sizing",
        value: "space",
        "translate": "translate",
        "translate-x": "translate-inline",
        "translate-y": "translate-block",
    },
    fontSize: {
        "set": "sizing",
        value: "text",
        "text": "font-size",
    },
    text: {
        "set": "colors",
        value: "all",
        "text": "color",
    },
    bg: {
        "set": "colors",
        value: "all",
        "bg": "background-color",
    }
}